$script = <<-SCRIPT
sudo runuser -l vagrant -c 'cat /tmp/authorized_keys >> /home/vagrant/.ssh/authorized_keys'
chown vagrant:vagrant /home/vagrant/.ssh/authorized_keys 
chmod 600 /home/vagrant/.ssh/authorized_keys
rm -f /tmp/authorized_keys
echo "Client done!"
SCRIPT

home = ENV['userprofile']

MACHINES = {

    :centoslinux => {
        :box_name => "centos/7",
        :box_version => "1.0",
        :ip_addr => '192.168.0.40',   #Your ip here
        :disks => {
            :sata1 => {
                :dfile => home + '/Virtualbox\ VMs/sata1.vdi',
                :size => 1024,
                :port => 2
            },
            :sata2 => {
                :dfile => home +'/Virtualbox\ VMs/sata2.vdi',
                :size => 1024, #Megabytes
                :port => 3
            }
       	}
    },

}


Vagrant.configure("2") do |config|

    MACHINES.each do |boxname, boxconfig|
        config.vm.define boxname do |box|

            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s 

            box.vm.network "public_network", ip: boxconfig[:ip_addr]

            box.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", "1024"] 
                vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]     

                boxconfig[:disks].each do |dname, dconf|

                    unless File.exist?(dconf[:dfile])
                        vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
                    end

                    vb.customize ['storageattach', :id, '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                    vb.gui = false
                    vb.cpus = 2
                end
 
                config.vm.provision "file", source: "authorized_keys", destination: "/tmp/authorized_keys"
                config.vm.provision "shell", inline: $script
            end

        end

    end
end
