web_servers:
  hosts:
    sa_cent:
    sa_ub:

all_hosts:
  children:
    education_machines:
      vars: 
        env: "prod"
      hosts:
        sa_cent:
          ansible_host: 192.168.254.50 
        sa_ub:
          ansible_host: 192.168.254.51
