---
apt_packages:
  - mc
  - nano
  - nginx
  - curl
  - gnupg-agent
  - apt-transport-https
  - ca-certificates
  - software-properties-common
  - docker-ce 
  - docker-ce-cli 
  - containerd.io
  - kubectl
