$script = <<-SCRIPT
sudo runuser -l vagrant -c 'cat /tmp/authorized_keys >> /home/vagrant/.ssh/authorized_keys'
chown vagrant:vagrant /home/vagrant/.ssh/authorized_keys 
chmod 600 /home/vagrant/.ssh/authorized_keys
rm -f /tmp/authorized_keys
echo "Client done!"
SCRIPT


Vagrant.configure("2") do |config|
	config.vm.box = "centos/7"
        config.vm.define "Centos_test"
	config.vm.network "public_network", ip: "192.168.0.240"
	config.vm.provider "virtualbox" do |vb|
       vb.gui = false
       vb.memory = 1500
       vb.cpus = 2
    end
    config.vm.provision "file",
	   source: "authorized_keys",
	   destination: "/tmp/authorized_keys"
	config.vm.provision "shell",
	   inline: $script
end
